server:
  port: 8085

spring:
  datasource:
    password:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  # http://localhost:8090/h2-console/
  h2:
    console:
      enabled: true
