
postgres:
  datasource:
    jdbc-url: "jdbc:mariadb://localhost:3306/test"
    password: root
    username: root

spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: false
  profiles:
    active: steklopod
  datasource:
    continue-on-error: true
#logging:
#  file: user-rebase.log