
csv.filename: "clients.csv"

mariadb:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    jdbc-url: "jdbc:mysql://127.0.0.1:3306/test"
    password: root
    username: root

sql-server:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: "jdbc:sqlserver://10.60.170.11:1433;database=steklopod"
    username: root
    password: root

spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
  profiles:
    active: steklopod
  datasource:
    continue-on-error: true
