
mariadb:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.2:3306/PROFILESERVICE?autoReconnect=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
    jdbc-url: "jdbc:mysql://127.0.0.2:3306/PROFILESERVICE?autoReconnect=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 4
    max-idle: 3
    max-wait: 10000
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

sql-server:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.3:3306/TASKSERVICE?autoReconnect=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
    jdbc-url: "jdbc:mysql://127.0.0.3:3306/TASKSERVICE?autoReconnect=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 4
    max-idle: 3
    max-wait: 10000
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8088

pool:
  connection.timeout: 10000
  idle.timeout: 60000
  size: 4
    # Это свойство управляет максимальным временем жизни соединения в пуле. Когда соединение достигнет
    # этого тайм-аута, даже если он используется недавно, он будет удален из пула. Входящее в действие
    # соединение никогда не будет удалено, только когда он простаивает, он будет удален.
  max.lifetime: 180000

spring:
  datasource:
    hikari:
      allow-pool-suspension: true
      connection-init-sql:  "SELECt 1"
      connection-timeout: 60000
      idle-timeout: 120000
      isolate-internal-queries: true
      minimum-idle: 1
      maximum-pool-size: 4
      max-lifetime: 180000

  jpa:
    database: default
    generate-ddl: true
    hibernate:
      ddl-auto:  create
      use-new-id-generator-mappings: true



#  datasource.type: com.zaxxer.hikari.HikariDataSource
#  application:
#    name: database-app
#  jackson:
#    serialization: true