
mariadb:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/test"
    jdbc-url: "jdbc:mysql://127.0.0.1:3306/test"
    password: root
    username: root

sql-server:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "jdbc:sqlserver://10.60.170.11:1433;database=StolotoSB"
    jdbc-url: "jdbc:sqlserver://10.60.170.11:1433;database=StolotoSB"
    username: "stoloto_ro"
    password: "3Dq3--uVQtM-d-xS"
    hibernate.dialect: "org.hibernate.dialect.SQLServer2012Dialect"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 4
    max-idle: 3
    max-wait: 10000

server:
  port: 8080

pool:
  connection.timeout: 10000
  idle.timeout: 60000
  size: 4
    # Это свойство управляет максимальным временем жизни соединения в пуле. Когда соединение достигнет
    # этого тайм-аута, даже если он используется недавно, он будет удален из пула. Входящее в действие
    # соединение никогда не будет удалено, только когда он простаивает, он будет удален.
  max.lifetime: 180000

spring:
  datasource:
    hikari:
      allow-pool-suspension: true
      connection-init-sql:  "SELECt 1"
      connection-timeout: 60000
      idle-timeout: 120000
      isolate-internal-queries: true
      minimum-idle: 1
      maximum-pool-size: 4
      max-lifetime: 180000

  jpa:
    database: default
    generate-ddl: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true


#  datasource.type: com.zaxxer.hikari.HikariDataSource
#  application:
#    name: database-app
#  jackson:
#    serialization: true